### ISSUE TITLE
Copy of PKP Hash

### ISSUE THREAD

**Issue by ericlaw1979** [vcsjones/FiddlerCert#1]
Maybe make the PKP hash label a LinkLabel that has the behavior, when clicked, of copying the appropriate HTTP Header string (including the name and prefix) to the clipboard? Show a message box indicating that this has been done? 

Also maybe have messagebox show info on best practices (e.g. must include on cert not in the chain, and should probably use an intermediate's hash not the EE)?

**Comment by vcsjones** [comment]
@ericlaw1979 I was tinkering with reworking this feature a bit, here are my plans, feedback appreciated.
1. On the view, rename "PKP Hash" to "SPKI Fingerprint" since this will show the hash of the public key regardless of whether or not its pinned.
2. If the SPKI fingerprint is pinned, put an indicator next to it like a thumbtack icon with a tooltip.
3. Clicking the thumbtack icon will show the full Public-Key-Pins header with the clicked fingerprint highlighted.

Eventually I want to get to the point where this will tell you about possible misconfigurations such as:
1. Only one key is pinned (browsers should ignore this and not have the desired affect)
2. If there is more than one fingerprint in the PKP header, display a warning if all of the pinned fingerprints appear in the chain. And have some documentation somewhere that a backup pin is required.
3. Using non-standard algorithms for pinning fingerprints. (RFC 7469 only allows SHA256 now)

**Comment by ericlaw1979** [comment]
This all sounds pretty awesome! :-)

**Comment by vcsjones** [comment]
A crude form of this has been added.
![screen shot 2015-08-14 at 11 38 31 am](https://cloud.githubusercontent.com/assets/361677/9277712/faa803c0-4279-11e5-8205-3b58d76ccc8a.png)

Things left to do:
- The pin indicator appears as long as the public-key-pins header is syntactically correct. If however it has mistakes that would otherwise prevent the UA for pinning, such as a missing backup pin, it will still show the pin indicator. In this case, I would expect the pin icon to appear to indicate an attempt to pin, but color it yellow with help information.
- ~~SHA1 pins should be warned. Some very early adopters pinned using SHA1, however SHA1 was removed from the RFC 7469 between drafts. However, Chrome _will_ pin a SHA1 SPKI today (version 44), thus the value in indicating it.~~
- ~~The Public-Key-Pins-Report-Only header is currently ignored.~~

**Comment by vcsjones** [comment]
I've decided to put the "validate the pins are correct" since many other tools already do it now (SSLLabs for example). The goal of this project is to focus mostly on the certificate itself.
