### ISSUE TITLE
Allow cert lookup on crt.sh

### ISSUE THREAD

**Issue by ericlaw1979** [vcsjones/FiddlerCert#14]
Display https://crt.sh/?q=[THUMBPRINT] 

e.g. https://crt.sh/?q=5BA7B281F76F69F2F6AE59916EBC8AA31700844A

obsoleting this script: https://gist.github.com/ericlaw1979/6dd32babc67233b62a30

**Comment by vcsjones** [comment]
This is a neat idea. Some thoughts that I can easily do:
1. Since Authenticode can have multiple signatures and a whole certificate chain, would be nice to be able to allow showing all certificates, timestamps, etc. AuthenticodeLint has the code to do this, so I can steal the hell out of that.
2. I like the immediate accessibility of it with a frame. As you otherwise noted, Inspector tabs can be a bit cramped. Since Certificate Inspector shows you a bunch of certificates, I'm not sure of the best way to display this. Using another tab as the script does feels weird since there needs to be some kind of user action of clicking the certificate they want to see in cert.sh. I'm not sure of the best way to do this that would fit in to Cert Inspector. Thoughts?

**Comment by vcsjones** [comment]
OK, here's my plan.
1. There will be another (drumroll...) _tab_ for certificate chains in _content_. A rough draft of the approach looks something like this:
   
   ![cqq5d34xgaa8ama](https://cloud.githubusercontent.com/assets/361677/17970260/d8a92a30-6aa3-11e6-93bf-87586704f0d2.jpg)
   
   This example uses the Firefox installer. This will make a best effort at extracting certificates from a variety of things. If the content is an Authenticode signed PE (exe, dll, etc) it will show all signing signatures. Since the implementation is borrowed from AuthenticodeLint it's possible to do for timestamps, but that seems a little out of scope to me. If  the object is just a .cer that got downloaded, it will show that. Theoretically anything that `CryptQueryObject` supports could be done, but I'll limit it to this for now.
2. OK, now back to the original request. Each certificate will have a `crt.sh` button, link, or something. When clicked, it will open a split-panel for crt.sh for that thumbprint. This link will exist for any certificate that Cert Inspector shows. Either the HTTP certificates, the content certificates, etc.
3. There will be an option to pop the link out of the split panel into the browser.
4. There will be a user pref for always popping open a browser instead of using the split panel. There will be no GUI for it, it'll be something that gets set in QuickExec for now.
5. You will be able to close to split panel.

This still means there are a number of clicks involved, either 1 or 2 if you need to switch from HTTP certificates to Content Certificates, then a button.

**Comment by vcsjones** [comment]
- [x] Add inspection of downloaded content.
- [x] Add crt.sh links for Thumbprint and SPKIs.
- [ ] Add an embedded web view for crt.sh.

**Comment by vcsjones** [comment]
The performance of crt.sh is... less than desirable, so I am going to leave it as links for now.
