### ISSUE TITLE
Perf: Disable revocation checking?

### ISSUE THREAD

**Issue by ericlaw1979** [vcsjones/FiddlerCert#5]
The current chain builder is doing online revocation checking by default. Unless that is desired, maybe we should set .NoCheck?

```
            X509Chain oChain = new X509Chain();
            oChain.ChainPolicy.RevocationMode = X509RevocationMode.NoCheck;
            oChain.Build(oEECert);
```

**Comment by vcsjones** [comment]
I hadn't considered the performance impact. It was intentional (though desirable is up for debate). The status icon (the cheesy shield I used) is green for All OK, which includes the revocation check. It is Yellow if we were unable to check revocation or offline revocation checking was performed, and red for everything else.

Perhaps checking revocation becomes a user-initiated action instead of doing it automatically.

**Comment by ericlaw1979** [comment]
Alternatively, you could do it async on another thread? We don't want to risk UI hangs as the user scrolls up and down the list.

**Comment by vcsjones** [comment]
Yes, I can do it async. I did the same thing for calculating the SPKI thumbprints.
